### ISSUE TITLE
Recurring Error

### ISSUE THREAD

**Issue by ef1972** [jcberquist/stripecfc#1]
Not sure why this is happening but I keep getting this error. Path is correct.

Invalid CFML construct found on line 358 at column 79.

ColdFusion was looking at the following text:
[

The CFML compiler was processing:

A script statement beginning with private on line 358, column 9.
 
The error occurred in /Applications/ColdFusion9/wwwroot/renters/miscellaneous/stripe.cfc: line 358

**Comment by jcberquist** [comment]
It looks like you are running ColdFusion 9, and the CFML compiler doesn't like the implicit array listed as the default value for the `params` agument in the the `apiCall()` function (which starts on line 358). Are you perhaps running on CF9 without any of the hotfixes or updates? I went back and looked at the first hotfix for CF9 and found bug id 80231 (see here: https://helpx.adobe.com/coldfusion/kb/cumulative-hot-fix-1-coldfusion.html), which states that implicit arrays didn't work as default values for the second argument of a function onward. If this is the version you are on, you would either need to update CF9 with the hotfix, or you could trying changing line 358 from `array params = [ ]` to `array params = arrayNew(1)`, and see if that works.

**Comment by ef1972** [comment]
Switching to  array params = arrayNew(1) gets rid of the initial error.

But new errors regarding the FOR loops occur.

Invalid CFML construct found on line 378 at column 17.ColdFusion was
looking at the following text:

for

The CFML compiler was processing:

   - A script statement beginning with for on line 378, column 17.
   - A script statement beginning with private on line 371, column 9.





Sorry bug you with all of this. If a solution does not jump out at you do
not worry about.
Erik

**Comment by jcberquist** [comment]
Yeah, you're definitely running CF9 with no updates. for...in array looping was fixed in CF9 update 1: https://helpx.adobe.com/coldfusion/kb/issues-fixed-coldfusion-9-0.html. (See Issue ID 80679.) I think at this point if you still want to use stripe.cfc you will need to update to at least CF 9.0.1 (or you can try working through the errors one by one, but that would be a pain). I do note in the Readme here that CF needs to be at least version 9.0.1

**Comment by ef1972** [comment]
OK. I will get the dev enviro updated. Luckily the production enviro is
updated. Thanks for the help and the stripe.cfc code.. I look forward to
getting this working.

Best,
Erik
